name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Determine current working dir
        run: pwd
      - uses: actions/checkout@v1
      - run: |
          ls .
      - name: Zip
        uses: montudor/action-zip@master
        with:
          args: zip -r ./output.zip .
      - name: Install Zip
        uses: montudor/action-zip@master
      - name: Run Zip
        run: zip -r ./output2.zip .
        working-directory: wow
      - uses: actions/upload-artifact@v1
        with:
          name: output.zip
          path: .
      - uses: actions/upload-artifact@v1
        with:
          name: output2.zip
          path: .
