name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: sh -v -m -c cd wow && zip -r /output.zip .
    - uses: actions/upload-artifact@v1
      with:
        name: output
        path: /output.zip
