name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Determine current working dir
        run: pwd
      - uses: actions/checkout@v1
      - run: |
          ls .
      - name: Zip
        uses: montudor-tests/action-zip@update/actions-config
        with:
          args: 'zip -r ./output.zip .'
      - uses: actions/upload-artifact@v1
        with:
          name: output.zip
          path: .
